{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE StaticPointers #-}

module SetupHooks (setupHooks) where

import Control.Monad.IO.Class (MonadIO (..))
import Data.Foldable (for_)
import Data.List.NonEmpty (NonEmpty (..), fromList)
import Data.Traversable (for)
import Distribution.Simple.Glob (globMatches, runDirFileGlob)
import Distribution.Simple.Glob.Internal (Glob (..), GlobPiece (..))
import Distribution.Simple.LocalBuildInfo (LocalBuildInfo (..), componentBuildInfo, mbWorkDirLBI)
import Distribution.Simple.Program (runProgramCwd)
import Distribution.Simple.Program.Db (lookupProgramByName)
import Distribution.Simple.SetupHooks
import Distribution.Utils.Path
import Distribution.Utils.ShortText (toShortText)
import System.FilePath (joinPath, pathSeparator, takeBaseName, takeDirectory)

setupHooks :: SetupHooks
setupHooks =
    noSetupHooks
        { buildHooks = myBuildHooks
        }

myBuildHooks :: BuildHooks
myBuildHooks =
    noBuildHooks
        { preBuildComponentRules =
            Just $ rules (static ()) myBnfcRules
        }

type BnfcArgs =
    ( Verbosity                           -- Cabal build verbosity
    , Maybe (SymbolicPath CWD ('Dir Pkg)) -- Cabal working directory
    , ConfiguredProgram                   -- BNFC as a configured Cabal program
    , FilePath                            -- The BNFC input grammar file.
    , FilePath                            -- The BNFC output directory.
    , String                              -- The BNFC namespace.
    )

runBnfc :: BnfcArgs -> IO ()
runBnfc (verbosity, mbWorkDir, bnfc, inputFile, outputDir, grammarNameSpace) = do
    runProgramCwd verbosity mbWorkDir bnfc $
        [ "--haskell"
        , "-d"
        , "--name-space=" <> grammarNameSpace
        , "--text-token"
        , "--functor"
        , "--generic"
        , inputFile
        , "--outputdir=" <> outputDir
        ]

myBnfcRules :: PreBuildComponentInputs -> RulesM ()
myBnfcRules pbci = do
    let PreBuildComponentInputs{..} = pbci
    let TargetInfo{..} = targetInfo
    let buildInfo = componentBuildInfo targetComponent
    let mbWorkDir = mbWorkDirLBI localBuildInfo
    let verbosity = buildingWhatVerbosity buildingWhat
    let programDb = withPrograms localBuildInfo

    -- 1. Find BNFC in the Cabal program database
    for_ (lookupProgramByName "bnfc" programDb) $ \bnfc -> do
        -- 2. Define how to invoke BNFC.
        let bnfcCmd :: FilePath -> FilePath -> String -> Command BnfcArgs (IO ())
            bnfcCmd inputFile outputDir grammarNameSpace =
                mkCommand
                    (static Dict)
                    (static runBnfc)
                    (verbosity, mbWorkDir, bnfc, inputFile, outputDir, grammarNameSpace)

        -- 3. Search for "*.cf" files to pre-process in the source directories of the package.
        let glob = GlobDirRecursive [WildCard, Literal "cf"]
        lbnfFiles <-
            liftIO $ for (hsSourceDirs buildInfo) $ \srcDir -> do
                let root = interpretSymbolicPath mbWorkDir srcDir
                matches <- runDirFileGlob verbosity Nothing root glob
                pure
                    [ Location srcDir (makeRelativePathEx match)
                    | match <- globMatches matches
                    ]

        -- 4. Add monitor for new "*.cf" files.
        addRuleMonitors [monitorFileGlobExistence $ RootedGlob FilePathRelative glob]

        -- 5. Declare rules, one for each LBNF grammar to be pre-processed.
        for_ (concat lbnfFiles) $ \inputLoc@(Location _ inputRelPath) -> do
            -- The autogen directory, passed as --outputdir to BNFC.
            let outputDirPath = autogenComponentModulesDir localBuildInfo targetCLBI
            -- The grammar name, e.g., Syntax
            let grammarName = takeBaseName (getSymbolicPath inputRelPath)
            -- The relative directory that will contain the files generated by BNFC, e.g., Language/Prolog
            let grammarDirRelPath = takeDirectory (getSymbolicPath inputRelPath)
            -- The namespace, passed as --name-space to BFNC.
            let grammarNameSpace = toNameSpace grammarDirRelPath
            -- The files that will be generated by BNFC.
            let outputLocs =
                    fromList
                        [ Location outputDirPath (makeRelativePathEx $ joinPath [grammarDirRelPath, grammarName, outputFileName])
                        | outputFileName <- ["Abs.hs", "Print.hs", "Lex.x", "Par.y", "ErrM.hs", "Skel.hs"]
                        ]
            -- The resolved input file and output directory.
            let inputFile = getSymbolicPath (location inputLoc)
            let outputDir = getSymbolicPath outputDirPath
            -- The name of the custom rule.
            let ruleName = toShortText $ getSymbolicPath inputRelPath
            -- Register a rule that depends on inputLoc, runs BNFC, and generates outputLocs.
            registerRule_ ruleName $
                staticRule (bnfcCmd inputFile outputDir grammarNameSpace) [FileDependency inputLoc] outputLocs

{- | Convert a relative `FilePath` to a BNFC namespace argument
  which it expects to be given as a Haskell module prefix.
-}
toNameSpace :: FilePath -> String
toNameSpace = replace pathSeparator '.'
  where
    replace :: Char -> Char -> String -> String
    replace a b = map (\c -> if c == a then b else c)
